[VG-8580] Fix screen's functions label
LedgerHQ/ledger-asset-dapps pull request #54
Opened 2022-08-10 14:32 UTC by mgrattepanche-ledger

### What is it about ? 

- Labels were not correctly conjugate. 
- Put "send" before "receive"

2022-08-10 15:20 UTC, slundy-ledger reviewed
"Minimum amount to be received" -> will this be displayed on the PSD ? i am afraid it won't fit the screen

2022-08-10 15:59 UTC, pcollet-ledger requested changes

2022-08-10 15:59 UTC, pcollet-ledger commented on ethereum/paraswap/parsers.json
> +                            "label": "Minimum amount to be received",
This does not match what we have on the figma right?
https://www.figma.com/file/BK1aCdRYEoRrfcmgtH5Xd1/Smart-Contract-Interactions-%26-dApp-Browser?node-id=646%3A7231

2022-08-10 15:59 UTC, pcollet-ledger commented on ethereum/paraswap/parsers.json
> +                            "label": "Minimum amount to be received",
This as well?

2022-08-16 13:05 UTC, mgrattepanche-ledger commented
Done through https://github.com/LedgerHQ/ledger-asset-dapps/pull/55/files I guess ... ?

2022-08-16 13:05 UTC, closed without merging